export type ProjectStory = {
  focus: string;
  experience: string[];
  takeaway: string;
  disciplines: string[];
};

export const stories: Record<string, ProjectStory> = {
  hoopr:{focus:'Connecting direction, cinematography and the rhythm of an edit.',experience:['My involvement in Hoopr moved across three parts of filmmaking: directing, shooting and editing. That gives this project a particular place in my portfolio—the creative contribution continues beyond a single stage of production.','I see those roles as connected decisions. Direction establishes what a moment needs to communicate, cinematography decides how we see it, and editing decides how we experience it over time.'],takeaway:'For me, the frame and the cut belong to the same conversation.',disciplines:['Direction','Cinematography','Editing']},
  milld:{focus:'A classroom-inspired story, with two different levels of involvement.',experience:['My Mill’d work includes two separate contributions. On the first video, I handled the script, direction, shooting and edit. On the second, I helped with direction.','The classroom-inspired concept brought character and a familiar cultural reference into the work. Across the two videos, my experience spans both carrying an idea through production and contributing to direction within a shared effort.'],takeaway:'Creative ownership also means being precise about where my contribution begins and ends.',disciplines:['Scriptwriting','Direction','Shooting','Editing','Direction support']},
  woktok:{focus:'Bringing performance and production into the same food ad.',experience:['For WokTok, my hands-on contribution to the video covered acting, shooting and editing.','Being on both sides of the camera gave this project a different scope: I was part of the performance and part of the choices that shaped its final presentation.'],takeaway:'A performance lives in the way it is filmed and edited, too.',disciplines:['Performance','Shooting','Editing']},
  'eat-kried':{focus:'Following a food-brand idea from the written concept through the edit.',experience:['My work for Eat Kried covered scripting, direction, shooting and editing. It is one of the projects where my involvement runs across the full creative sequence.','This is the part of production I’m drawn to: staying close to an idea as it changes form.'],takeaway:'I want to stay with a story long enough to help it become a finished piece.',disciplines:['Scriptwriting','Direction','Shooting','Editing']},
  'green-packaging':{focus:'Using food packaging to explore the relationship between perception and choice.',experience:['Green Packaging sits at the intersection of my psychology background and my interest in food storytelling. For Margins & Meals, I explored what makes a product look healthy before we have even read its label.','My contribution covered the script, direction, shooting and editing.'],takeaway:'An everyday object can be the opening scene of a much bigger question.',disciplines:['Research','Scriptwriting','Direction','Shooting','Editing']},
  'popcorn-pricing':{focus:'Turning a familiar cinema purchase into a food-and-business story.',experience:['This Margins & Meals episode begins with a simple cinema question: why does the popcorn cost so much?','I scripted, directed, shot and edited the video, bringing food and cinema into the same story through the lens of business.'],takeaway:'The story around food can be as interesting as the food itself.',disciplines:['Research','Scriptwriting','Direction','Shooting','Editing']},
  sportsyard:{focus:'Beginning with brand research before deciding what to make.',experience:['My contribution to Sportsyard was brand research. This entry represents the part of my creative practice that happens before a script, shoot or visual identity.'],takeaway:'A useful creative starting point is a question worth investigating.',disciplines:['Brand research']},
  'epicure-robotics':{focus:'Translating precision and food operations into a visual identity.',experience:['Epicure Robotics gave me a storytelling problem: how to express a business through an identity system.','My exploration connected E + R with references to robotic arms and mechanical forms, with applications across cups and a vending machine.'],takeaway:'An identity needs a point of view, and places where that point of view can live.',disciplines:['Rebranding','Logo exploration','Visual identity','Applications']},
  cotopay:{focus:'Connecting landing-page structure, competitor research and motion.',experience:['My CotoPay work focused on a landing page, supported by a review of competing expense-management experiences.','I explored how movement through micro-interactions, parallax and blur could support the page’s visual story.'],takeaway:'Motion is most useful when it gives attention a direction.',disciplines:['Competitor research','Landing-page design','Interaction exploration']},
  'framer-hosting':{focus:'An independent exploration of how to communicate speed and security.',experience:['This was an independent redesign exploration for Framer’s hosting page. I organised the concept around speed and security, with a feature spotlight structure underneath.'],takeaway:'A strong headline needs a clear structure underneath it.',disciplines:['Web design','Content hierarchy','Feature presentation']},
  'krismar-marbles':{focus:'Bringing performance-marketing research into a pitch.',experience:['For Krismar Marbles, my contribution was performance-marketing research and pitch development. This project represents my strategy work: developing the thinking behind a recommendation and shaping it into a presentation.'],takeaway:'The reason behind a creative recommendation should be as clear as the recommendation itself.',disciplines:['Performance-marketing research','Pitch development']},
  bsff:{focus:'A registration-focused social campaign for people who care about film.',experience:['The Bengaluru Short Film Festival brief brought my interest in cinema into campaign planning. The objective was to maximise registrations, with cinephiles and potential film producers as the core audiences.','My planning focused on the lead-up to the event and communication that could move people towards registering.'],takeaway:'A film event needs a story about why someone should be in the room.',disciplines:['Campaign planning','Audience strategy','Social communication']},
  'house-of-andhra':{focus:'Turning an Andhra food sub-brand into a clearer marketing story.',experience:['House of Andhra was a sub-brand project within DIL Foods. I worked on the brand through the marketing-mix lens, using the 7Ps to think through how the offer should come together across product, price, place, promotion, people, process and physical evidence.','What interested me was the balance between food, regional identity and the systems around the brand. The work gave me a strategy layer alongside the storytelling and production work already represented in my portfolio.'],takeaway:'A food brand is not just what is on the plate; it is the world built around it.',disciplines:['Brand strategy','7Ps framework','Marketing planning']},
  'asan-cup':{focus:'Making menstrual-cup adoption feel approachable for a Gen Z first-timer.',experience:['For Asan Cup, I worked on a six-month Gen Z campaign built around a very human barrier: the uncertainty of trying a menstrual cup for the first time.','The creative direction explored approachable content rather than clinical instruction, including a “girlfriend’s guide” route and the idea of making the first step feel genuinely simple.'],takeaway:'Good communication can make an intimidating first step feel like a conversation.',disciplines:['Campaign strategy','Content planning','Copywriting','Audience insight']},
  phurr:{focus:'Turning a Mumbai restaurant launch into something people could discover, not just see.',experience:['For PHURR, I worked on the influencer-marketing strategy for a Mumbai launch, with storytellers at the centre rather than a generic food-influencer list. The creator approach was built around people who could make Mumbai itself part of the story.','The launch narrative developed into a mystery: a PHURR mascot, clues, a missing-person-style poster and the question “PHURR KUTHE AAHE?” The goal was to create curiosity before revealing the restaurant, giving creators a reason to participate in a story rather than simply publish an announcement.'],takeaway:'The best launch is sometimes the one that makes people ask, “wait—what is this?”',disciplines:['Influencer marketing strategy','Creator mapping','Campaign narrative','Content planning']}
};
