export const projects=[
{slug:'hoopr',name:'Hoopr',cat:'Film & production',roles:'Direction · Cinematography · Editing',line:'Finding the feeling in the frame.',brief:'A video project for Hoopr.',work:'I worked across direction, shooting and editing, connecting what happened on set with the rhythm of the final cut.',format:'Brand video',type:'Brand project',cover:'SOUND / VISION',color:'olive'},
{slug:'milld',name:'Mill’d',cat:'Film & production',roles:'Writing · Direction · Cinematography · Editing',line:'A little classroom chaos.',brief:'A classroom-inspired video concept for Mill’d, drawing on the energy of a Rancho-style character.',work:'For the first video, I wrote, directed, shot and edited. On a second video, I supported direction.',format:'Two video contributions',type:'Brand project',cover:'CLASS / ACT',color:'wine'},
{slug:'woktok',name:'WokTok',cat:'Film & production',roles:'Performance · Cinematography · Editing',line:'On both sides of the camera.',brief:'A UGC-style food ad for WokTok.',work:'I acted, shot and edited the video, moving between the performance and the choices that shaped its final pacing.',format:'UGC-style ad',type:'Brand project',cover:'WOK / TOK',color:'rust'},
{slug:'eat-kried',name:'Eat Kried',cat:'Film & production',roles:'Writing · Direction · Cinematography · Editing',line:'An idea, taken all the way to the cut.',brief:'A food-brand video for Eat Kried.',work:'I handled scripting, direction, shooting and editing across the project.',format:'Brand video',type:'Brand project',cover:'CRAVE / CREATE',color:'stone'},
{slug:'green-packaging',name:'Green Packaging',cat:'Film & production',roles:'Research · Writing · Direction · Shooting · Editing',line:'Does green really mean good?',brief:'An episode for my YouTube channel, Margins & Meals, exploring green packaging and the illusion of healthy food.',work:'I developed the story around how visual cues influence food perception, using packaging colour comparisons and a sugar-cube reveal to make the question tangible.',format:'YouTube explainer',type:'Independent work',cover:'GREEN ≠ GOOD',color:'green'},
{slug:'popcorn-pricing',name:'The Price of Popcorn',cat:'Film & production',roles:'Research · Writing · Direction · Shooting · Editing',line:'The real story behind the snack.',brief:'A Margins & Meals video exploring why movie-theatre popcorn costs so much.',work:'I scripted, directed, shot and edited the episode, bringing my interest in food and business into a familiar cinema experience.',format:'YouTube explainer',type:'Independent work',cover:'EXTRA / LARGE',color:'wine'},
{slug:'sportsyard',name:'Sportsyard',cat:'Creative strategy',roles:'Brand research',line:'Starting with the right questions.',brief:'A brand research project for Sportsyard.',work:'My contribution focused on researching the brand. Detailed research materials are not included in this edition of the portfolio.',format:'Brand research',type:'Research project',cover:'PLAY / THINK',color:'olive'},
{slug:'epicure-robotics',name:'Epicure Robotics',cat:'Design',roles:'Rebranding · Visual identity',line:'Precision, with a human appetite.',brief:'A rebranding and identity-system project for a food-operations robotics brand.',work:'I explored an E + R identity informed by robotic arms, mechanical forms and precision, with applications across cups and a vending machine. The positioning centred on scalable, consistent, autonomous food operations.',format:'Identity system',type:'Design project',cover:'E / R',color:'stone'},
{slug:'cotopay',name:'CotoPay',cat:'Design',roles:'Landing-page design · Competitor research',line:'Making a complex offer feel clear.',brief:'A landing-page design project for CotoPay.',work:'I reviewed competing expense-management experiences and explored hero micro-interactions, parallax and blur as part of the page’s visual direction.',format:'Website design',type:'Design project',cover:'COTO / PAY',color:'green'},
{slug:'framer-hosting',name:'Framer Hosting',cat:'Design',roles:'Web design · Content hierarchy',line:'Speed, with structure.',brief:'An independent redesign exploration for Framer’s hosting page.',work:'I organised the concept around speed and security, exploring a feature spotlight grid and the headline “Global scale hosting, engineered for speed and security.”',format:'Page redesign',type:'Independent concept',cover:'BUILT / FAST',color:'olive'},
{slug:'krismar-marbles',name:'Krismar Marbles',cat:'Creative strategy',roles:'Performance-marketing research · Pitch',line:'Giving the pitch a solid foundation.',brief:'A performance-marketing research and pitch project for Krismar Marbles.',work:'My contribution covered research and pitch development. Campaign performance figures have not been supplied.',format:'Research & pitch',type:'Strategy project',cover:'FORM / INTENT',color:'stone'},
{slug:'bsff',name:'Bengaluru Short Film Festival',cat:'Creative strategy',roles:'Campaign planning · Audience strategy',line:'Finding the people who live for film.',brief:'A social campaign-planning brief to grow registrations for a three-day film festival.',work:'The plan focused on cinephiles and potential film producers, with registration-oriented communication across the lead-up to the festival. This is a planning case, with no verified campaign results included.',format:'Social campaign plan',type:'Campaign concept',cover:'SHORT / STORIES',color:'wine'},
{slug:'house-of-andhra',name:'House of Andhra',cat:'Creative strategy',roles:'Brand strategy · 7Ps · Creative planning',line:'Where spice meets soul.',brief:'A brand and marketing exploration for House of Andhra, a sub-brand of DIL Foods.',work:'I worked on the House of Andhra sub-brand through its marketing mix, looking at the brand across product, price, place, promotion and the wider 7Ps framework.',format:'Brand strategy',type:'Brand project',cover:'SPICE / SOUL',color:'rust'},
{slug:'asan-cup',name:'Asan Cups',cat:'Creative strategy',roles:'Campaign strategy · Content planning · Copy',line:'Making the first step feel less intimidating.',brief:'A Gen Z-focused campaign for Asan Cup, built around making menstrual-cup adoption feel approachable for first-time users.',work:'I developed campaign thinking and content directions around the first-use barrier, including the “girlfriend’s guide” content route and the core idea of making the experience feel simple rather than intimidating.',format:'Campaign strategy',type:'Brand campaign',cover:'FIRST / TIME',color:'wine'},
{slug:'phurr',name:'PHURR',cat:'Creative strategy',roles:'Campaign strategy · Creator marketing · Storytelling',line:'A bird, a city, and a secret worth following.',brief:'A Mumbai launch campaign for PHURR built around creators, clues and the experience of discovering the brand.',work:'I worked on the influencer-marketing strategy and launch narrative, focusing on Mumbai-based storytellers and creators who could turn PHURR into a city-wide mystery rather than a conventional restaurant announcement.',format:'Influencer marketing strategy',type:'Brand campaign',cover:'PHURR / KUTHE AAHE?',color:'green'}
];
export type Project = (typeof projects)[number];
